services:
  misp-core:
    environment:
      NUM_WORKERS_DEFAULT: ${NUM_WORKERS_DEFAULT:-1}
      NUM_WORKERS_PRIO: ${NUM_WORKERS_PRIO:-1}
      NUM_WORKERS_EMAIL: ${NUM_WORKERS_EMAIL:-1}
      NUM_WORKERS_UPDATE: ${NUM_WORKERS_UPDATE:-1}
      NUM_WORKERS_CACHE: ${NUM_WORKERS_CACHE:-1}
